-- ===================================================================
-- CREATE TICKET STATUS UPDATES FEATURE
-- ===================================================================
-- This script creates the necessary table, indexes, policies, triggers
-- and functions for the custom status updates feature.
-- 
-- Run this script in your Supabase SQL Editor or via CLI migration
-- ===================================================================

-- Create ticket_status_updates table for custom progress updates
CREATE TABLE IF NOT EXISTS public.ticket_status_updates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id UUID NOT NULL REFERENCES public.service_tickets(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    update_text TEXT NOT NULL CHECK (length(update_text) > 0 AND length(update_text) <= 1000),
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_system_update BOOLEAN DEFAULT FALSE NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_ticket_status_updates_ticket_id ON public.ticket_status_updates(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_status_updates_status ON public.ticket_status_updates(status);
CREATE INDEX IF NOT EXISTS idx_ticket_status_updates_created_at ON public.ticket_status_updates(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ticket_status_updates_created_by ON public.ticket_status_updates(created_by);

-- Add RLS (Row Level Security) policies
ALTER TABLE public.ticket_status_updates ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read all status updates for tickets they have access to
CREATE POLICY "Users can read status updates for accessible tickets" 
ON public.ticket_status_updates 
FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM public.service_tickets st 
        WHERE st.id = ticket_status_updates.ticket_id 
        AND auth.uid() IS NOT NULL
    )
);

-- Policy: Users can insert status updates for tickets they have access to
CREATE POLICY "Users can create status updates for accessible tickets" 
ON public.ticket_status_updates 
FOR INSERT 
WITH CHECK (
    auth.uid() IS NOT NULL AND
    EXISTS (
        SELECT 1 FROM public.service_tickets st 
        WHERE st.id = ticket_status_updates.ticket_id
    )
    AND created_by = auth.uid()
);

-- Policy: Users can only update their own status updates
CREATE POLICY "Users can update their own status updates" 
ON public.ticket_status_updates 
FOR UPDATE 
USING (created_by = auth.uid() AND auth.uid() IS NOT NULL)
WITH CHECK (created_by = auth.uid() AND auth.uid() IS NOT NULL);

-- Policy: Users can delete their own status updates (not system updates)
CREATE POLICY "Users can delete their own status updates" 
ON public.ticket_status_updates 
FOR DELETE 
USING (
    created_by = auth.uid() 
    AND auth.uid() IS NOT NULL 
    AND is_system_update = FALSE
);

-- Create trigger function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_ticket_status_updates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the trigger
CREATE TRIGGER trigger_update_ticket_status_updates_updated_at
    BEFORE UPDATE ON public.ticket_status_updates
    FOR EACH ROW
    EXECUTE FUNCTION public.update_ticket_status_updates_updated_at();

-- Grant necessary permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ticket_status_updates TO authenticated;

-- Add helpful comments
COMMENT ON TABLE public.ticket_status_updates IS 'Custom status updates for service tickets - allows team members to add progress notes at any stage';
COMMENT ON COLUMN public.ticket_status_updates.ticket_id IS 'Reference to the service ticket';
COMMENT ON COLUMN public.ticket_status_updates.status IS 'The ticket status when this update was added (reported, triaged, in_progress, completed, delivered)';
COMMENT ON COLUMN public.ticket_status_updates.update_text IS 'The progress update text (max 1000 characters)';
COMMENT ON COLUMN public.ticket_status_updates.created_by IS 'User who added this update';
COMMENT ON COLUMN public.ticket_status_updates.is_system_update IS 'Whether this update was automatically generated by the system (vs manually added by user)';
